server:
  port: 9002
spring:
  application:
    name: user-auth
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    url: jdbc:mysql://10.210.4.74:3306/opms_staff?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true
    username: root
      #          password:
    password: rfkj_iims
  main:
    allow-bean-definition-overriding: true
mybatis:
  ##xml文件的路径配置
  mapper-locations: classpath:mybatis/*.xml


eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
auth:
  ttl: 3600 #token存储到redis的过期时间
  clientId: changgou
  clientSecret: changgou
  cookieDomain: localhost
  cookieMaxAge: -1
encrypt:
  key-store:
    location: classpath:/changgou.jks
    secret: changgou
    alias: changgou
    password: changgou
logging:
  level:
    com.szkingdom.rfkj.oauth.dao: debug
