server:
  port: 9001
spring:
  application:
    name: user-auth
  datasource:
    url: jdbc:mysql://10.210.4.74:3306/opms_staff?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true
    username: root
      #          password:
    password: rfkj_iims
  main:
    allow-bean-definition-overriding: true
mybatis:
  ##xml文件的路径配置
  mapper-locations: classpath:mybatis/*.xml
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
logging:
  level:
    com.szkingdom.rfkj.oauth.dao: debug
